# Generated by Django 2.2.15 on 2020-10-20 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enlace', models.CharField(max_length=150, verbose_name='Enlace de la Herramienta')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar Enlace')),
            ],
            options={
                'verbose_name_plural': 'Enlaces de Herramientas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Herramienta')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción')),
                ('fotografia', models.ImageField(default='herramienta/image.jpg', help_text='Suba imágenes (jpg, gif, png).', upload_to='plataforma/')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones_sugerencias', models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Describa las observaciones y sugerencias')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Herramienta descontinuada')),
                ('enlace', models.ForeignKey(help_text='Seleccione el Enlace.', on_delete=django.db.models.deletion.PROTECT, to='herramientas.Enlace')),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
                'ordering': ['id'],
            },
        ),
    ]
