# Generated by Django 2.2.15 on 2020-10-20 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_auto_20201020_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='observaciones_sugerencias',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Describa las observaciones y sugerencias'),
        ),
    ]
