# Generated by Django 2.2.15 on 2020-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_auto_20201020_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='fotografia',
            field=models.ImageField(default='herramienta/image.jpg', help_text='Suba imágenes (jpg, gif, png).', upload_to='herramienta/'),
        ),
    ]
