# Generated by Django 2.2.15 on 2020-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_auto_20201020_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
