# Generated by Django 2.2.15 on 2020-10-20 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del área')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción del área')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar área')),
            ],
            options={
                'verbose_name_plural': 'Áreas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enlace', models.CharField(max_length=150, verbose_name='Enlace de la Herramienta')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar Enlace')),
            ],
            options={
                'verbose_name_plural': 'Enlaces de Herramientas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Herramienta')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción')),
                ('enlace', models.URLField(help_text='Escriba la dirección completa incluido http:// o https://', max_length=255, verbose_name='Enlace')),
                ('fotografia', models.ImageField(default='herramienta/image.jpg', help_text='Suba imágenes (jpg, gif, png).', upload_to='plataforma/')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones_sugerencias', models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Describa las observaciones y sugerencias')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Herramienta descontinuada')),
            ],
            options={
                'verbose_name_plural': 'Herramientas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nivel Académico')),
                ('Descripcion', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Descripción del Nivel Académico')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Ocultar Nivel Académico')),
            ],
            options={
                'verbose_name_plural': 'Niveles Académicos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Plataforma')),
                ('objetivo', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Objetivo de la Plataforma')),
                ('enlace', models.URLField(help_text='Escriba la dirección completa incluido http:// o https://', max_length=255, verbose_name='Enlace')),
                ('fotografia', models.ImageField(blank=True, help_text='Suba imágenes (jpg, gif, png).', upload_to='plataforma/')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones_sugerencias', models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)], verbose_name='Describa las observaciones y sugerencias')),
                ('ocultar', models.BooleanField(default=False, verbose_name='Plataforma descontinuada')),
                ('area', models.ManyToManyField(help_text='Seleccione las áreas de la plataforma.', to='plataforma.Area')),
                ('nivel', models.ManyToManyField(help_text='Seleccione los niveles académicos ofrecidos por la plataforma.', to='plataforma.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Plataformas',
                'ordering': ['id'],
            },
        ),
    ]
