# Generated by Django 2.2.15 on 2020-10-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='enlace',
            field=models.ForeignKey(help_text='Seleccione el Enlace.', on_delete=django.db.models.deletion.PROTECT, to='plataforma.Enlace'),
        ),
    ]
