# Generated by Django 2.2.15 on 2020-10-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20201019_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='enlace',
        ),
        migrations.DeleteModel(
            name='Enlace',
        ),
        migrations.DeleteModel(
            name='Herramienta',
        ),
    ]
