# Generated by Django 2.2.15 on 2020-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20201020_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='nivel',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
